### ISSUE TITLE
Error installing Multiwfn through homebrew

### ISSUE THREAD

**Issue by vpostils** [kjelljorner/homebrew-multiwfn#1]
Dear digital-chemistry-laboratory,

    For the last couple of days, I've been trying to install multiwfn in my MacOs Monterey Version 12.6 and the compilation process did not finish properly due to the following error. 

(I did not use OpenMP. Thus, I was using the command: brew install --HEAD digital-chemistry-laboratory/multiwfn/multiwfn)
"" 
==> cmake -S . -B build
==> cmake --build build
Last 15 lines from /Users/vpostils/Library/Logs/Homebrew/multiwfn/02.cmake:
      |                  1
Warning: Deleted feature: End expression in DO loop at (1) must be integer
/usr/local/Cellar/cmake/3.26.4/bin/cmake -E cmake_copy_f90_mod libreta.mod CMakeFiles/multiwfn.dir/libreta.mod.stamp GNU
/usr/local/Cellar/cmake/3.26.4/bin/cmake -E touch CMakeFiles/multiwfn.dir/libreta_hybrid/libreta.f90.o.provides.build
[ 56%] Building Fortran object CMakeFiles/multiwfn.dir/function.f90.o
/usr/local/bin/gfortran   -O3 -DNDEBUG -O3 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk -ffree-line-length-none -cpp -c /tmp/multiwfn-20230524-51806-57i06y/function.f90 -o CMakeFiles/multiwfn.dir/function.f90.o
/tmp/multiwfn-20230524-51806-57i06y/function.f90:1560:7:

 1560 |   use mod_2F2, only: GTO_fractional_integral
      |       1
Fatal Error: Cannot open module file 'mod_2f2.mod' for reading at (1): No such file or directory
compilation terminated.
make[2]: *** [CMakeFiles/multiwfn.dir/function.f90.o] Error 1
make[1]: *** [CMakeFiles/multiwfn.dir/all] Error 2
make: *** [all] Error 2

""" 

I do not know if you could help me in solving the previous issue. Any correction or guide you could provide would be really grateful. 
Otherwise, I am just reporting this issue to you as it is suggested in the installation process.

All the best,

Verònica Postils
_Ramón Areces post-doctoral researcher
UBordeaux_

**Comment by kjelljorner** [comment]
Thanks for raising the issue. Multiwfn updates sometimes break the build process. I made some progress to update it, but it needs some changes in the original source that I have submitted to the original Multiwfn author. After that goes through I can update first https://github.com/digital-chemistry-laboratory/multiwfn-mac-build and then the homebrew tap.

**Comment by vpostils** [comment]
Thank you a lot for all your effort and attention to this issue, kjelljorner!! 
I'll wait for the updates with much interest. 
And thank you again for this nice Multiwfn's installation help you are providing!

**Comment by kjelljorner** [comment]
I updated the build process and it works for me now. Let me know if it works for you as well.

**Comment by vpostils** [comment]
Dear kjelljorner,
It works for me as well. Yesterday (after a long compilation time) I managed to install multiwfn on my Mac (without OpenMP interface). Today I have just configured the settings.ini file and done some small tests. I think it works perfectly. 
Thank you a lot, again, for your initiative and for sharing it! 
I will spread the word. Sorry for my delay in responding.

**Comment by kjelljorner** [comment]
Great to hear @vpostils and thanks for spreading the word! The compilation is indeed slow as it is optimizing and homebrew only compiles with one core as far as I know. The OpenMP also works well in my experience and gives you a speedup during program runs. For newer Macs with Apple Silicon, in my experience you can set this at least to the number of "performance cores" that you have. I will close this issue now.
