### ISSUE TITLE
can not install using brew

### ISSUE THREAD

**Issue by lucl13** [kjelljorner/homebrew-multiwfn#2]
can not install using brew, it gives the following error:

```

Last 15 lines from /Users/chenlin/Library/Logs/Homebrew/multiwfn/02.cmake:                                             /opt/homebrew/include/arb.h:1041:11: error: 'count_leading_zeros' is deprecated. Use 'flint_clz' instead.
 1041 |             count_leading_zeros(bits, t);
      |           ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
gmake[2]: *** [CMakeFiles/multiwfn.dir/build.make:404: CMakeFiles/multiwfn.dir/ext/2F2.c.o] Error 1
gmake[2]: *** Waiting for unfinished jobs....
/tmp/multiwfn-20231230-20088-ylrnn6/libreta_hybrid/boysfunc.f90:67:13:

   67 |                     DO I=2,NOTRMS
      |                           1
Warning: Deleted feature: End expression in DO loop at (1) must be integer
gmake[2]: Leaving directory '/private/tmp/multiwfn-20231230-20088-ylrnn6/build'
gmake[1]: *** [CMakeFiles/Makefile2:86: CMakeFiles/multiwfn.dir/all] Error 2
gmake[1]: Leaving directory '/private/tmp/multiwfn-20231230-20088-ylrnn6/build'
gmake: *** [Makefile:139: all] Error 2


If reporting this issue please do so at (not Homebrew/brew or Homebrew/homebrew-core):
  https://github.com/digital-chemistry-laboratory/homebrew-multiwfn/issues

multiwfn's formula was built from an unstable upstream --HEAD.
This build failure is expected behaviour.
Do not create issues about this on Homebrew's GitHub repositories.
Any opened issues will be immediately closed without response.
Do not ask for help from Homebrew or its maintainers on social media.
You may ask for help in Homebrew's discussions but are unlikely to receive a response.
Try to figure out the problem yourself and submit a fix as a pull request.


```

**Comment by kjelljorner** [comment]
Thanks for reporting. It relates to a recent breaking change in some of the dependencies of Multiwfn. It would need to be resolved by the maintainer directly in the source. I have reached out to him and we can see when it can be resolved.

**Comment by foxtran** [comment]
@lucl13, could you please show a full log?

@kjelljorner, After merging arb with flint 3.0, CMake does not need to link arb library (and this library must not be on user computer) with MultiWFN. Corresponding `acb_hypgeom.h` should be taken from flint distribution if flint's version >= 3.0.

**Comment by kjelljorner** [comment]
@foxtran I have tried that, problem is that the include for the new `acb_hypergeom.h` does not lead to the recursive include of `acb.h` that was present in the old one. Therefore there will be undefined symbols in `2F2C.c` and it will fail to compile. This cannot be fixed apart from a change of the source code of `2F2C.c` from what I can tell.

**Comment by foxtran** [comment]
Aha...

Original version in arb includes `acb.h`:
https://github.com/fredrik-johansson/arb/blob/af15c0070a6d9fbc551a2cbf23364387233b18e3/acb_hypgeom.h#L15-L16

While flint loads only necessary headers:
https://github.com/flintlib/flint/blob/622f0310fe8c034a2bbc7bfcda70bbed670aee93/src/acb_hypgeom.h#L15

**Comment by lucl13** [comment]
sorry for the late reply. I tested it and can install it now.

**Comment by kjelljorner** [comment]
Thanks for checking @lucl13!
